export const QUIZ_QUESTIONS = [
    { id: 1, text: "Do you experience tremors in hands, arms, legs, jaw, or head?", name: "q1" },
    { id: 2, text: "Have you noticed slowness in daily movements like walking or eating?", name: "q2" },
    { id: 3, text: "Do you experience stiffness or rigidity in limbs or trunk?", name: "q3" },
    { id: 4, text: "Do you have trouble with balance or tend to fall?", name: "q4" },
    { id: 5, text: "Has your walking changed (e.g., shuffling, slow start)?", name: "q5" },
    { id: 6, text: "Do you lean forward or stoop while walking?", name: "q6" },
    { id: 7, text: "Has your face become less expressive or more blank?", name: "q7" },
    { id: 8, text: "Do your arms swing less while walking?", name: "q8" },
    { id: 9, text: "Has your handwriting become smaller or harder to read?", name: "q9" },
    { id: 10, text: "Do you struggle with fine finger tasks like buttoning clothes?", name: "q10" },
    { id: 11, text: "Do you have trouble smelling things (loss of smell)?", name: "q11" },
    { id: 12, text: "Do you act out dreams (e.g., punch, kick, talk)?", name: "q12" },
    { id: 13, text: "Do you feel sleepy during the day despite full sleep?", name: "q13" },
    { id: 14, text: "Do you feel anxious, depressed, or disinterested?", name: "q14" },
    { id: 15, text: "Do you forget things or struggle to make decisions?", name: "q15" },
    { id: 16, text: "Do you feel dizzy or faint when you stand up?", name: "q16" },
    { id: 17, text: "Do you feel constipated frequently?", name: "q17" },
    { id: 18, text: "Have others noticed changes in behavior or thinking?", name: "q18" },
    { id: 19, text: "Are there any symptoms that bother you which haven’t been asked?", name: "q19" },
    { id: 20, text: "Have you been diagnosed with Parkinson's disease by a medical professional?", name: "q20" },
];
